@Library('ci-shared-lib') _

pipeline {
    agent any

    environment {
        AWS_REGION = "us-east-1"
        AWS_ACCOUNT_ID = credentials('aws-account-id')
        IMAGE_NAME = "finalprojectapp"
        IMAGE_TAG = "${BUILD_NUMBER}"
        APPDIR = "app"
        K8SMANIFESTSDIR = "k8s"
        ECR_URI = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${IMAGE_NAME}"
        GIT_BRANCH_NAME = "${env.BRANCH_NAME ?: env.GIT_BRANCH?.replace('origin/', '')}"
    }
    stages {
        stage('Build Docker Image') {
            steps {
                BuildImage(APPDIR, IMAGE_NAME, IMAGE_TAG)
            }
        }

        stage('Scan Docker Image') {
            steps {
                ScanImage(IMAGE_NAME, IMAGE_TAG)
            }
        }
        stage('Push Docker Image to ECR') {
            steps {
                PushImage(IMAGE_NAME, IMAGE_TAG, AWS_ACCOUNT_ID, AWS_REGION)
            }
        }
        stage('Remove Local Docker Image') {
            steps {
                RemoveImageLocally(IMAGE_NAME, IMAGE_TAG)
            }
        }
        stage('Update K8s Manifests') {
            steps {
                UpdateK8sManifests(K8SMANIFESTSDIR, ECR_URI, IMAGE_TAG)
            }
        }
        stage('Push Updated Manifests') {
            steps {
                script {
                    def repoUrl = scm.getUserRemoteConfigs()[0].getUrl()
                    withCredentials([usernamePassword(credentialsId: 'github-creds', usernameVariable: 'GIT_USER', passwordVariable: 'GIT_PASS')]) {
                        PushK8sManifests(K8SMANIFESTSDIR, IMAGE_TAG, repoUrl, GIT_BRANCH_NAME)
                    }
                }
            }
        }
    }
    post {
        always {
            echo "Pipeline finished."
        }
        success {
            echo "Pipeline succeeded!"
        }
        failure {
            echo "Pipeline failed!"
        }
    }
}