@Library('ci-shared-lib') _

pipeline {
	agent {
		any
	}
	environment {
		IMAGE_REPO = "therealqi"
		IMAGE_NAME = "clouddevopsgradproject"
		IMAGE_TAG = "${BUILD_NUMBER}"
		APPDIR = "app"
		K8SMANIFESTSDIR = "k8s"
	}
	stages {
		stage('Build Docker Image') {
			steps {
				BuildImage(APPDIR, IMAGE_REPO, IMAGE_NAME, IMAGE_TAG)
			}
		}
		stage('Scan Docker Image') {
			steps {
				ScanImage(IMAGE_REPO, IMAGE_NAME, IMAGE_TAG)
			}
		}
		stage('Push Docker Image') {
			steps {
				withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'DOCKERHUB_USER', passwordVariable: 'DOCKERHUB_PASS')]) {
					PushImage(IMAGE_REPO, IMAGE_NAME, IMAGE_TAG)
				}
			}
		}
		stage('Remove Local Docker Image') {
			steps {
				RemoveImageLocally(IMAGE_REPO, IMAGE_NAME, IMAGE_TAG)
			}
		}
		stage('Update K8s Manifests') {
			steps {
				UpdateManifest(K8SMANIFESTSDIR, IMAGE_REPO, IMAGE_NAME, IMAGE_TAG)
			}
		}
		stage('Push Updated Manifests') {
			steps {
				withCredentials([usernamePassword(credentialsId: 'github-creds', usernameVariable: 'GIT_USER', passwordVariable: 'GIT_PASS')]) {
					PushToGit(K8SMANIFESTSDIR, IMAGE_TAG)
				}
			}
		}
	}

	post {
		always {
			echo "Pipeline finished."
		}
		success {
			echo "Pipeline succeeded!"
		}
		failure {
			echo "Pipeline failed!"
		}
	}
}
